version: 2.1
jobs:
  test_simple_latest:
    docker:
      - image: euantorano/zig:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: print zig version
          command: |
            zig version
      - run:
          name: run tests
          command: |
            zig build test
          working_directory: ~/repo/simple

  test_simple_master:
    docker:
      - image: euantorano/zig:master
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: print zig version
          command: |
            zig version
      - run:
          name: run tests
          command: |
            zig build test
          working_directory: ~/repo/simple

  test_sdl_latest:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: build docker image
          command: |
            docker build -t zig-sdl2 ./sdl/
      - run:
          name: print zig version
          command: |
            docker run zig-sdl2 version
      - run:
          name: build app
          command: |
            docker run -v ~/repo/sdl:/app zig-sdl2 build
          working_directory: ~/repo/sdl
      


workflows:
  version: 2
  commit:
    jobs:
      - test_simple_latest
      - test_simple_master
      - test_sdl_latest